### ISSUE TITLE
Please release more often

### ISSUE THREAD

**Issue by jirutka** [daurnimator/lpeg_patterns#7]
Long time no release, it’s blocking e.g. https://github.com/daurnimator/lua-http/issues/36. Could you please release a new version soon?

**Comment by daurnimator** [comment]
We're not blocked (only) on a release. Mainly blocked on the merge of #2.
I'd appreciate code reviews if anyone has the requisite knowledge.

**Comment by daurnimator** [comment]
0.3 release is out :tada:
